@startuml lbutils_pmods_gpio
namespace lbutils {
    namespace pmods {
        namespace gpio {
            class LED {
                + led0 : bool
                + led1 : bool
                + led2 : bool
                + led3 : bool
                + set_state()
                }
        }
}

@enduml
